#!/bin/bash
curl -X 'POST' \
  'http://127.0.0.1:8888/v1/generation/text-to-image' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "prompt":                 "8k Resolution, photo-realistic, sailing on a sunny day with a clear blue sky, consistent water horizon",
  "negative_prompt":        "unrealistic, saturated, high contrast, painting, drawing, sketch, cartoon, anime, manga, render, CG, 3d, watermark, signature, labels",
  "style_comment":          "genMetadata includes the [ ] around the styles",  
  "style_selections":        ["Photo Iphone Photographic"],
  "performance_selection":  "Speed",
  "aspect_ratios_selection":"640*640",
  "image_number":            1,
  "image_seed":              -1,
  "sharpness":               2.0,
  "guidance_scale":          4.5,
  "base_model_name":        "juggernautXL_v8Rundiffusion.safetensors",
  "refiner_model_name":     "None",
  "refiner_switch":          1.0,
  "loras": [
    { "enabled": true, "model_name": "Doll Likeness DollLikenessv1.safetensors", "weight": 1 },
    { "enabled": true, "model_name": "None", "weight": 1 },
    { "enabled": true, "model_name": "None", "weight": 1 },
    { "enabled": true, "model_name": "None", "weight": 1 },
    { "enabled": true, "model_name": "None", "weight": 1 } ],
  "advanced_params": {
    "overwrite_step":        25,
    "adaptive_cfg": 7.06,
    "adm_scaler_end": 0.3,
    "adm_scaler_negative": 0.8,
    "adm_scaler_positive": 1.5,
    "black_out_nsfw": false,
    "canny_high_threshold": 128,
    "canny_low_threshold": 64,
    "clip_skip": 2,
    "controlnet_softness": 0.25,
    "debugging_cn_preprocessor": false,
    "debugging_inpaint_preprocessor": false,
    "disable_intermediate_results": false,
    "disable_preview": false,
    "disable_seed_increment": false,
    "freeu_b1": 1.01,
    "freeu_b2": 1.02,
    "freeu_enabled": false,
    "freeu_s1": 0.99,
    "freeu_s2": 0.95,
    "inpaint_disable_initial_latent": false,
    "inpaint_engine": "v2.6",
    "inpaint_erode_or_dilate": 0,
    "inpaint_mask_upload_checkbox": false,
    "inpaint_respective_field": 1,
    "inpaint_strength": 1,
    "invert_mask_checkbox": false,
    "mixing_image_prompt_and_inpaint": false,
    "mixing_image_prompt_and_vary_upscale": false,
    "overwrite_height": -1,
    "overwrite_switch": -1,
    "overwrite_upscale_strength": -1,
    "overwrite_vary_strength": -1,
    "overwrite_width": -1,
    "refiner_swap_method": "joint",
    "sampler_name": "dpmpp_2m_sde_gpu",
    "scheduler_name": "karras",
    "skipping_cn_preprocessor": false,
    "vae_name": "Default (model)"
  },
  "save_name": "myJob_0012_steps_25_resolution_640x640_guidance_scale_4.5_sharpness_2.0_042147",
  "save_meta": true,
  "meta_scheme": "fooocus",
  "save_extension": "png",
  "read_wildcards_in_order": true,
  "require_base64": false,
  "async_process": false,
  "webhook_url": ""
}'

status=$?
echo "Exit status: $status"
exit $status

